config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
 
  get '/help'      => 'static_pages#help'
 
  get '/about'     => 'static_pages#about'
 
  get '/signup'    => 'users#new'
 
  get '/login'     => 'sessions#new'

  post '/login'    => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  # post '/create' => 'users#create', as:'users'

  # get '/:id/'    => 'users#show', as:'user'
  resources :microposts, only: [:create, :destroy]
  resources :users, except: :new do
    member do  #memberメソッドを使うとユーザーidがURLに含まれるように扱う
      get :following, :followers #/users/:id/followers(.:format)
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]


	#GET /users/1/following  following following_user_path(1)
  #GET /users/1/followers  followers followers_user_path(1

end

app/views/layouts/_footer.html.erb
<p>footer</p>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default navbar-inverse">
<div class="container">
		<%= link_to "AwesomeBlog", root_path, class: "navbar-brand" %>
  	<ul class="nav navbar-nav navbar-right">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>

        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>

          <li><%= link_to "Log in", login_path %></li>
        <% end %>
<!-- 			<li><%#= link_to "About", about_path %></li>
 -->
		</ul>
	</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/header" %>
    <div class="container">

      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
         <%= message %>
      </div>
      <% end %>
      <%= yield %>

    </div>
    <%= render "/layouts/footer" %>

  </body>
</html>